version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: estacio_project
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  app:
    build: ./app
    container_name: python_app
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: estacio_project
      DATABASE_USER: user
      DATABASE_PASSWORD: password
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  postgres_data:
