version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:3002"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
